[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.80.0"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"

[[redirects]]
  from = "https://tomjenkins.netlify.app/2020/08/17/dna-extraction/"
  to = "https://tomjenkins.netlify.app/project/dna-extraction/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "https://tomjenkins.netlify.app/2020/09/21/r-popgen-getting-started/"
  to = "https://tomjenkins.netlify.app/tutorials/r-popgen-getting-started/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "https://tomjenkins.netlify.app/2020/10/26/r-extract-marine-data/"
  to = "https://tomjenkins.netlify.app/tutorials/r-extract-marine-data/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
  